export enum CDDA_JSON_TYPES {
  MOD_INFO = 'MOD_INFO',
  profession = 'profession',
  scenario = 'scenario',
  start_location = 'start_location',
  furniture = 'furniture',
  gate = 'gate',
  terrain = 'terrain',
  trap = 'trap',
  item_group = 'item_group',
  ammunition_type = 'ammunition_type',
  AMMO = 'AMMO',
  ARMOR = 'ARMOR',
  BIONIC_ITEM = 'BIONIC_ITEM',
  BOOK = 'BOOK',
  GENERIC = 'GENERIC',
  TOOL = 'TOOL',
  COMESTIBLE = 'COMESTIBLE',
  GUNMOD = 'GUNMOD',
  GUN = 'GUN',
  TOOL_ARMOR = 'TOOL_ARMOR',
  harvest = 'harvest',
  SPELL = 'SPELL',
  MONSTER_FACTION = 'MONSTER_FACTION',
  monstergroup = 'monstergroup',
  MONSTER = 'MONSTER',
  SPECIES = 'SPECIES',
  speech = 'speech',
  dream = 'dream',
  mutation_category = 'mutation_category',
  mutation = 'mutation',
  talk_topic = 'talk_topic',
  faction = 'faction',
  mission_definition = 'mission_definition',
  npc_class = 'npc_class',
  npc = 'npc',
  trait_group = 'trait_group',
  mapgen = 'mapgen',
  ter_furn_transform = 'ter_furn_transform',
  overmap_special = 'overmap_special',
  overmap_terrain = 'overmap_terrain',
  region_overlay = 'region_overlay',
  city_building = 'city_building',
  requirement = 'requirement',
  recipe = 'recipe',
  recipe_category = 'recipe_category',
  uncraft = 'uncraft',
  enchantment = 'enchantment',
  achievement = 'achievement',
  ammo_effect = 'ammo_effect',
  bionic = 'bionic',
  clothing_mod = 'clothing_mod',
  effect_type = 'effect_type',
  emit = 'emit',
  field_type = 'field_type',
  json_flag = 'json_flag',
  martial_art = 'martial_art',
  material = 'material',
  scent_type = 'scent_type',
  skill = 'skill',
  snippet = 'snippet',
  technique = 'technique',
  vehicle_part = 'vehicle_part',
  overlay_order = 'overlay_order',
  mod_tileset = 'mod_tileset',
  palette = 'palette',
  event_statistic = 'event_statistic',
  event_transformation = 'event_transformation',
}

export interface ICDDAJSON<Type extends CDDA_JSON_TYPES = CDDA_JSON_TYPES.MOD_INFO> {
  type: Type;
  id?: string;
  name?: string | { str: string; str_pl?: string };
  description?: string;
  authers?: string[];
  maintainers?: string[];
  category?: string;
  dependencies?: string[];
  monsters?: string[];
}
