export interface IEffectType {
  type: 'effect_type';
  id: string;
  '//'?: string;
  name?: Array<Name | string>;
  desc?: string[];
  int_add_val?: number;
  max_intensity?: number;
  base_mods?: Basemods;
  show_in_info?: boolean;
  apply_message?: string;
  rating?: string;
  remove_message?: string;
  max_duration?: number | string;
  scaling_mods?: Scalingmods;
  remove_memorial_log?: string;
  apply_memorial_log?: string;
  int_dur_factor?: number | string;
  removes_effects?: string[];
  blood_analysis_description?: string;
  miss_messages?: Array<Array<number | string>>;
  resist_traits?: string[];
  pain_sizing?: boolean;
  hurt_sizing?: boolean;
  main_parts_only?: boolean;
  show_intensity?: boolean;
  max_effective_intensity?: number;
  dur_add_perc?: number;
  int_decay_tick?: number;
  harmful_cough?: boolean;
  flags?: string[];
  pkill_addict_reduces?: boolean;
  part_descs?: boolean;
  speed_name?: string;
  resist_effects?: string[];
  blocks_effects?: string[];
  decay_messages?: string[][];
  '//1'?: string;
  '//2'?: string;
  '//3'?: string;
  int_decay_step?: number;
}

interface Scalingmods {
  speed_mod?: number[];
  pain_max_val?: number[];
  pain_chance?: number[];
  pain_min?: number[];
  hurt_chance?: number[];
  str_mod?: number[];
  dex_mod?: number[];
  stamina_min?: number[];
  stamina_chance?: number[];
  int_mod?: number[];
  per_mod?: number[];
  pain_chance_bot?: number[];
  vomit_chance?: number[];
  fatigue_chance?: number[];
  healing_rate?: number[];
  hurt_min?: number[];
  pkill_tick?: number[];
  pkill_min?: number[];
  pkill_max_val?: number[];
  thirst_min?: number[];
  thirst_tick?: number[];
  stamina_max?: number[];
  fatigue_min?: number[];
  fatigue_tick?: number[];
  sleep_chance?: number[];
  fatigue_max?: number[];
  h_mod_min?: number[];
  h_mod_min_val?: number[];
  h_mod_chance?: number[];
  health_min?: number[];
  health_min_val?: number[];
  vomit_tick?: number[];
  hit_mod?: number[];
  dodge_mod?: number[];
  bash_mod?: number[];
  size_mod?: number[];
  cough_chance?: number[];
  pain_amount?: number[];
  hurt_amount?: number[];
}

interface Basemods {
  speed_mod?: number[];
  per_mod?: number[];
  dex_mod?: number[];
  str_mod?: number[];
  pain_min?: number[];
  pain_chance?: number[];
  pain_max_val?: number[];
  pain_chance_bot?: number[];
  hurt_min?: number[];
  hurt_chance?: number[];
  hurt_max?: number[];
  pain_amount?: number[];
  hurt_amount?: number[];
  hurt_tick?: number[];
  stamina_amount?: number[];
  stamina_min?: number[];
  stamina_chance?: number[];
  vomit_chance?: number[];
  vomit_tick?: number[];
  cough_chance?: number[];
  stim_tick?: number[];
  stim_min?: number[];
  stim_min_val?: number[];
  pkill_tick?: number[];
  pkill_min?: number[];
  pkill_max_val?: number[];
  fatigue_min?: number[];
  fatigue_chance?: number[];
  fatigue_tick?: number[];
  pain_tick?: number[];
  healing_rate?: number[];
  healing_head?: number[];
  healing_torso?: number[];
  int_mod?: number[];
  rad_chance?: number[];
  rad_min?: number[];
  thirst_tick?: number[];
  thirst_chance?: number[];
  thirst_min?: number[];
  sleep_chance?: number[];
  sleep_min?: number[];
  sleep_max?: number[];
  pkill_amount?: number[];
  stim_chance?: number[];
  hunger_chance?: number[];
  hunger_min?: number[];
  h_mod_chance?: number[];
  h_mod_min?: number[];
  pain_max?: number[];
  thirst_max_val?: number[];
  hurt_chance_bot?: number[];
  stamina_max?: number[];
  fatigue_max?: number[];
  h_mod_min_val?: number[];
  h_mod_chance_bot?: number[];
  h_mod_tick?: number[];
  health_chance?: number[];
  health_min?: number[];
  hit_mod?: number[];
  dodge_mod?: number[];
  bash_mod?: number[];
  fatigue_amount?: number[];
  stim_amount?: number[];
}

interface Name {
  ctxt: string;
  str: string;
}
